name: deploy-aws-lambda
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2
      - name: Deploy code to Lambda
        uses: kohrongying/py-lambda-action@v1.0.3
        with:
          lambda_layer_arn: 'arn:aws:lambda:ap-southeast-1:163368111864:layer:PIL-layer'
          lambda_function_name: 'test'
          lambda_layer_publish: false
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'ap-southeast-1'